export const REQUIRED_ELEMENT_SELECTORS = Object.freeze({
  mainContent: "main",
  setupForm: "[data-setup-form]",
  setupStatus: "[data-setup-status]",
  setupReviewButton: "[data-review-setup]",
  setupCreateButton: "[data-create-session]",
  setupAddAntennaButton: "[data-add-antenna]",
  useCurrentLocationButton: "[data-use-current-location]",
  locationStatus: "[data-location-status]",
  stationGrid: '[data-setup-field="grid"]',
  setupAntennaTemplate: "[data-antenna-template]",
  setupFeedback: "[data-setup-feedback]",
  setupFeedbackMessage: "[data-setup-feedback-message]",
  setupFeedbackDetail: "[data-setup-feedback-detail]",
  setupDiagnostics: "[data-setup-diagnostics]",
  setupReviewPanel: "[data-setup-review]",
  setupReviewStation: "[data-review-station]",
  setupReviewAntennas: "[data-review-antennas]",
  setupReviewShape: "[data-review-shape]",
  setupReviewSlots: "[data-review-slots]",
  setupRunPlanSummary: "[data-run-plan-summary]",
  conductorPanel: "[data-conductor]",
  conductorEmpty: "[data-conductor-empty]",
  conductorStatus: "[data-conductor-status]",
  conductorLifecycle: "[data-conductor-lifecycle]",
  conductorAntennaInUse: "[data-conductor-antenna-in-use]",
  conductorPhase: "[data-conductor-phase]",
  conductorGuidance: "[data-conductor-guidance]",
  conductorCountdown: "[data-conductor-countdown]",
  currentSlot: "[data-current-slot]",
  nextSlot: "[data-next-slot]",
  evidenceForm: "[data-evidence-form]",
  entryPanel: "[data-entry-panel]",
  correctionsPanel: "[data-corrections-panel]",
  addRunNote: "[data-add-run-note]",
  openCorrections: "[data-open-corrections]",
  evidenceKind: "[data-evidence-kind]",
  evidenceSlot: "[data-evidence-slot]",
  evidenceAntenna: "[data-evidence-antenna]",
  evidenceFrequency: "[data-evidence-frequency]",
  evidenceMode: "[data-evidence-mode]",
  evidencePower: "[data-evidence-power]",
  evidenceCallsign: "[data-evidence-callsign]",
  evidenceCadence: "[data-evidence-cadence]",
  evidenceDetail: "[data-evidence-detail]",
  conductorFeedback: "[data-conductor-feedback]",
  conductorFeedbackMessage: "[data-conductor-feedback-message]",
  conductorFeedbackDetail: "[data-conductor-feedback-detail]",
  conductorDiagnostics: "[data-conductor-diagnostics]",
  conductorEvents: "[data-conductor-events]",
  wsprLivePhase: "[data-wspr-live-phase]",
  wsprLiveDetail: "[data-wspr-live-detail]",
  wsprLiveDiagnostic: "[data-wspr-live-diagnostic]",
  wsprLiveRetry: "[data-wspr-live-retry]",
  wsprLiveEndWithout: "[data-wspr-live-end-without]",
  wsjtxForm: "[data-wsjtx-form]",
  wsjtxBindAddress: "[data-wsjtx-bind-address]",
  wsjtxPort: "[data-wsjtx-port]",
  wsjtxClientId: "[data-wsjtx-client-id]",
  wsjtxStart: "[data-wsjtx-start]",
  wsjtxStop: "[data-wsjtx-stop]",
  wsjtxPhase: "[data-wsjtx-phase]",
  wsjtxRequirement: "[data-wsjtx-requirement]",
  wsjtxCounts: "[data-wsjtx-counts]",
  wsjtxDiagnostic: "[data-wsjtx-diagnostic]",
  openButton: "[data-open-session]",
  exportButton: "[data-export-session]",
  importWsprLiveButton: "[data-import-wspr-live]",
  importRbnButton: "[data-import-rbn]",
  transferStatus: "[data-transfer-status]",
  openFeedback: "[data-open-feedback]",
  feedbackMessage: "[data-feedback-message]",
  feedbackDetail: "[data-feedback-detail]",
  exportFeedback: "[data-export-feedback]",
  exportFeedbackMessage: "[data-export-feedback-message]",
  exportFeedbackDetail: "[data-export-feedback-detail]",
  importFeedback: "[data-import-feedback]",
  importFeedbackMessage: "[data-import-feedback-message]",
  importFeedbackDetail: "[data-import-feedback-detail]",
  reportStatus: "[data-report-status]",
  reportPlaceholder: "[data-report-placeholder]",
  reportViewer: "[data-report-viewer]",
  reportFrame: "[data-report-frame]",
  reportBundleName: "[data-report-bundle]",
  reportRevision: "[data-report-revision]",
  reportSummary: "[data-report-summary]",
  reportRefreshButton: "[data-report-refresh]",
  reportExportButton: "[data-report-export]",
  reportFeedback: "[data-report-feedback]",
  reportFeedbackMessage: "[data-report-feedback-message]",
  reportFeedbackDetail: "[data-report-feedback-detail]",
});

export const REQUIRED_ELEMENT_LIST_SELECTORS = Object.freeze({
  navigation: "[data-workflow]",
  panels: "[data-panel]",
  conductorRefreshButtons: "[data-conductor-refresh]",
  lifecycleButtons: "[data-conductor-action]",
});

export function collectDesktopElements(root) {
  const elements = {};
  for (const [name, selector] of Object.entries(REQUIRED_ELEMENT_SELECTORS)) {
    const element = root.querySelector(selector);
    if (!element) throw new Error(`Missing required desktop element ${name}: ${selector}`);
    elements[name] = element;
  }
  for (const [name, selector] of Object.entries(REQUIRED_ELEMENT_LIST_SELECTORS)) {
    const matches = [...root.querySelectorAll(selector)];
    if (matches.length === 0) throw new Error(`Missing required desktop element list ${name}: ${selector}`);
    elements[name] = matches;
  }
  return elements;
}
