#!/usr/bin/env bash
# -*- mode: sh; sh-shell: bash; -*-
#MISE description="Run CI checks"

set -euo pipefail

mise run toolchain
mise run supply-chain
mise run desktop:e2e
mise run desktop:frontend-test
mise run fmt
mise run lint
mise run test
